### ISSUE TITLE
会出错

### ISSUE THREAD

**Issue by JXH-2020** [Sknp1006/rk-rtsp#2]
![image](https://github.com/Sknp1006/rk-rtsp/assets/67779513/06c69e73-2414-4f9a-b89b-f4b0c40ed48f)

**Comment by Sknp1006** [comment]
Thanks for the issues.Can you provide more information about your operating environment,such as:
- SoC(RK3588/RK356X or others)
- OS version
- ffmpeg version
- rockchip_mpp version
- libdrm version
...

I think it's ffmpeg's fault.
