### ISSUE TITLE
内存泄漏 博主 我在瑞芯微rk3588上跑的

### ISSUE THREAD

**Issue by Sknp1006** [Sknp1006/rk-rtsp#3]
内存泄漏 博主 我在瑞芯微rk3588上跑的

_Originally posted by @JXH-2020 in https://github.com/Sknp1006/rk-rtsp/issues/1#issuecomment-2331005804_
            
最新代码也泄露吗，之前修复过了

**Comment by JXH-2020** [comment]
![image](https://github.com/user-attachments/assets/2f9d236c-ded4-48bc-bb10-0e1216c43c09)

**Comment by JXH-2020** [comment]
这样就不泄露了

**Comment by JXH-2020** [comment]
运行了一段时间会出现
![image](https://github.com/user-attachments/assets/4d5e2ecf-8648-4c8d-8b5a-3b23528f2930)

**Comment by Sknp1006** [comment]
main.cpp有 free 掉这里的内存，看看你拉的代码有没有

**Comment by Sknp1006** [comment]
<img width="306" alt="image" src="https://github.com/user-attachments/assets/5e90cd28-4280-4ee0-85cd-f1177a42608f">
